// <auto-generated />
using System;
using EFStore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFStore.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20220514072105_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFStore.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2002c723-cee3-4b47-9fa7-ea0a631a41f4"),
                            Name = "Cat1"
                        },
                        new
                        {
                            Id = new Guid("a6863264-e507-439b-b383-56848125bc13"),
                            Name = "Cat2"
                        },
                        new
                        {
                            Id = new Guid("f5a17e95-ca1d-43e1-841b-bf02929453f3"),
                            Name = "Cat3"
                        });
                });

            modelBuilder.Entity("EFStore.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d341767c-aee0-4f33-8af4-c6b9ba3fbca5"),
                            Manufacture = "M1",
                            Name = "Pro1"
                        },
                        new
                        {
                            Id = new Guid("c74e68e5-c38c-4686-8adc-cc821c85bba4"),
                            Manufacture = "M2",
                            Name = "Pro2"
                        },
                        new
                        {
                            Id = new Guid("9c8236d7-9d72-4d62-8866-8aa037b744e2"),
                            Manufacture = "M3",
                            Name = "Pro3"
                        });
                });

            modelBuilder.Entity("EFStore.Models.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("d341767c-aee0-4f33-8af4-c6b9ba3fbca5"),
                            CategoryId = new Guid("f5a17e95-ca1d-43e1-841b-bf02929453f3")
                        },
                        new
                        {
                            ProductId = new Guid("c74e68e5-c38c-4686-8adc-cc821c85bba4"),
                            CategoryId = new Guid("2002c723-cee3-4b47-9fa7-ea0a631a41f4")
                        },
                        new
                        {
                            ProductId = new Guid("9c8236d7-9d72-4d62-8866-8aa037b744e2"),
                            CategoryId = new Guid("a6863264-e507-439b-b383-56848125bc13")
                        });
                });

            modelBuilder.Entity("EFStore.Models.Entities.ProductCategory", b =>
                {
                    b.HasOne("EFStore.Models.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFStore.Models.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EFStore.Models.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EFStore.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
